### PR TITLE
Update LTI for Canvas

### PR DESCRIPTION
**Pull request by andrew-gardener**
- Existing LTI courses will need to manually have their lti parameters migrated from loginlist_lti to the course's settings table to allow automatic updates
- Added $bridge{launch_auto_manage_user_roles} to control which user roles are allowed to launch into webwork (all accounts will be automatically created/updated when a user launches into webwork)
- Automatic updates will no longer fail if membership is not available
- Launch requests will now fill in user.lis_source_did for course contexts and set_user.lis_source_did when linking to a homework set though custom_homework_set or custom_quiz
- LTI grade passback will now use a decimal score (canvas doesn't seem to support ratio)
- LTI grade passback for gateway assignments will now passback the best score (since passing back the grades for each version won't work with opaque lis_source_did
- updated the automatic update scripts to check each course for the lti_automatic_updates flag in the course settings table instead of checking listing in loginlist_lti. This also allowed to simplify the scripts in many ways.

### CODE REVIEW

**Comment by andrew-gardener** [comment]
@xcompass I added a setting for automatic hiding of new lti courses (code here https://github.com/ubc/webwork2/pull/4/files#diff-988e36f0f79ecc412bb8a1aac2412dc6R77)

**Comment by xcompass** [comment]
Great. Could you add a flag to enable/disable that automatic hiding feature?

**Comment by andrew-gardener** [comment]
Did that already https://github.com/ubc/webwork2/pull/4/files#diff-852a279db2450e7d5ec105a9092706e5R478

**Comment by xcompass** [comment]
Great. For some reason, my mind completely skipped that if statement....https://github.com/ubc/webwork2/pull/4/files#diff-988e36f0f79ecc412bb8a1aac2412dc6R78

**Pull request merged**
